__default__:
    h_data: 6G
    h_rt: 12:00:0
    threads: 1
star_map:
    h_data: 35G
    h_rt: 02:00:00,highp
    threads: 1
star_con:
    h_data: 36G
    h_rt: 02:00:00
    threads: 1
clam_prep:
    h_data: 28G
    h_rt: 8:00:0,highp
    threads: 1
clam_prep_con:
    h_data: 12G
    h_rt: 8:00:0
    threads: 1
clam_callpeak:
    h_data: 18G
    h_rt: 18:00:0
    threads: 1
clam_callpeak_mread:
    h_data: 18G
    h_rt: 18:00:0
    threads: 1
macs2:
    h_data: 18G
    h_rt: 24:00:0
    threads: 1
clam_em:
    h_data: 28G
    h_rt: 8:00:0,highp
    threads: 1
clam_em_ip:
    h_data: 18G
    h_rt: 12:00:0
    threads: 1
homer_motif:
    h_data: 6G
    h_rt: 1:00:0
homer_motif_rescue:
    h_data: 6G
    h_rt: 1:00:0
homer_motif_macs2:
    h_data: 6G
    h_rt: 1:00:0
make_bw:
    h_data: 8G
    h_rt: 24:00:0
kallisto_quant:
    h_data: 8G
    h_rt: 4:00:0
