hg19:
    star_idx: /u/nobackup/yxing/NOBACKUP/frankwoe/hg19/star_idx_gencode_v19
    gtf: /u/nobackup/yxing/NOBACKUP/frankwoe/hg19/gencode.v19.annotation.gtf
mm10:
    star_idx: /u/nobackup/yxing/NOBACKUP/frankwoe/mm10/star_idx_gencodeM13
    gtf: /u/nobackup/yxing/NOBACKUP/frankwoe/mm10/gencode.vM13.annotation.gtf
